# Generated by Django 3.2.6 on 2023-03-03 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fully_approved', models.BooleanField(default=False, verbose_name='Fully Approved')),
                ('level_1_approval', models.CharField(max_length=200, unique=True, verbose_name='level_1_approval Name')),
                ('level_2_approval', models.CharField(max_length=200, unique=True, verbose_name='level_2_approval Name')),
                ('level_3_approval', models.CharField(max_length=200, unique=True, verbose_name='level_3_approval Name')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=200, unique=True, verbose_name='Design Name')),
                ('design_slug', models.SlugField(null=True, unique=True, verbose_name='Design Slug')),
                ('is_editable', models.BooleanField(default=False, verbose_name='Editable')),
                ('design_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design.approval', verbose_name='Design Approval')),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Designs',
                'ordering': ('id', 'design_name'),
            },
        ),
    ]
