# Generated by Django 3.2.6 on 2023-03-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='level_1_approval',
            field=models.CharField(max_length=200, verbose_name='Level 1 Approver User Name'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='level_2_approval',
            field=models.CharField(max_length=200, verbose_name='Level 2 Approver User Name'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='level_3_approval',
            field=models.CharField(max_length=200, verbose_name='Level 3 Approver User Name'),
        ),
    ]
