# Generated by Django 3.2.6 on 2021-11-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookExample',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('detail_text', models.TextField()),
                ('detail_json', models.JSONField()),
            ],
            options={
                'verbose_name': 'Book Example',
                'verbose_name_plural': 'Book Examples',
                'db_table': 'book_example',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contacts Info',
            },
        ),
    ]
