# Generated by Django 3.2.6 on 2021-09-26 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=200, unique=True, verbose_name='Publisher Name')),
                ('publisher_slug', models.SlugField(null=True, unique=True, verbose_name='Publisher Slug')),
                ('publisher_status', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
                'ordering': ('id', 'publisher_name'),
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=200, unique=True, verbose_name='Software Name')),
                ('software_slug', models.SlugField(null=True, unique=True)),
                ('software_status', models.BooleanField(default=False, verbose_name='Active')),
                ('software_version', models.CharField(max_length=200, null=True, verbose_name='Software Version')),
                ('software_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restify.publisher')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Software',
                'ordering': ('id', 'software_name'),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=200, unique=True, verbose_name='Server Name')),
                ('server_slug', models.SlugField(null=True, unique=True)),
                ('server_status', models.BooleanField(default=False, verbose_name='Active')),
                ('server_software', models.ManyToManyField(blank=True, to='restify.Software')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'ordering': ('id', 'server_name'),
            },
        ),
    ]
