# Generated by Django 3.2.6 on 2021-10-02 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ait_number', models.IntegerField(unique=True, verbose_name='Ait #')),
                ('ait_slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'AIT',
                'verbose_name_plural': 'AITs',
                'ordering': ('id', 'ait_number'),
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_name', models.CharField(max_length=200, verbose_name='Environment Name')),
                ('environment_slug', models.SlugField(null=True, unique=True)),
                ('environment_status', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Environment',
                'verbose_name_plural': 'Environments',
                'ordering': ('id', 'environment_name'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, unique=True, verbose_name='Project Name')),
                ('project_slug', models.SlugField(null=True, unique=True)),
                ('project_status', models.BooleanField(default=False, verbose_name='Active')),
                ('project_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restify.ait', verbose_name='Project AIT #')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('id', 'project_name'),
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=200, unique=True, verbose_name='Publisher Name')),
                ('publisher_slug', models.SlugField(null=True, unique=True, verbose_name='Publisher Slug')),
                ('publisher_status', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
                'ordering': ('id', 'publisher_name'),
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=200, verbose_name='Software Name')),
                ('software_slug', models.SlugField(null=True, unique=True)),
                ('software_status', models.BooleanField(default=False, verbose_name='Active')),
                ('software_version', models.CharField(max_length=200, null=True, verbose_name='Software Version')),
                ('software_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restify.publisher')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Software',
                'ordering': ('id', 'software_name'),
                'unique_together': {('software_name', 'software_version')},
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=200, unique=True, verbose_name='Server Name')),
                ('server_slug', models.SlugField(null=True, unique=True)),
                ('server_status', models.BooleanField(default=False, verbose_name='Active')),
                ('server_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restify.ait', verbose_name='Server AIT')),
                ('server_environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restify.environment', verbose_name='Server Environment')),
                ('server_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restify.project', verbose_name='Server Project')),
                ('server_software', models.ManyToManyField(blank=True, to='restify.Software', verbose_name='Server Software')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'ordering': ('id', 'server_name'),
            },
        ),
        migrations.AddField(
            model_name='environment',
            name='environment_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restify.project', verbose_name='environment_project - Project Environment'),
        ),
    ]
