# Generated by Django 3.2.6 on 2021-09-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restify', '0002_alter_software_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='software_name',
            field=models.CharField(max_length=200, verbose_name='Software Name'),
        ),
    ]
