# Generated by Django 3.2.6 on 2021-10-02 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restify', '0003_alter_software_software_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ait_number', models.IntegerField(unique=True, verbose_name='Ait #')),
                ('ait_slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'AIT',
                'verbose_name_plural': 'AITs',
                'ordering': ('id', 'ait_number'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, unique=True, verbose_name='Project Name')),
                ('project_slug', models.SlugField(null=True, unique=True)),
                ('project_status', models.BooleanField(default=False, verbose_name='Active')),
                ('project_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restify.ait', verbose_name='Project AIT #')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('id', 'project_name'),
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_name', models.CharField(max_length=200, unique=True, verbose_name='Environment Name')),
                ('environment_slug', models.SlugField(null=True, unique=True)),
                ('environment_status', models.BooleanField(default=False, verbose_name='Active')),
                ('environment_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restify.project', verbose_name='Environment Project')),
            ],
            options={
                'verbose_name': 'Environment',
                'verbose_name_plural': 'Environments',
                'ordering': ('id', 'environment_name'),
            },
        ),
        migrations.AddField(
            model_name='server',
            name='server_environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restify.environment', verbose_name='Server Environment'),
        ),
        migrations.AddField(
            model_name='server',
            name='server_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restify.project', verbose_name='Server Project'),
        ),
    ]
