# Generated by Django 3.2.6 on 2023-04-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.IntegerField(verbose_name='Active Record')),
                ('cpu', models.IntegerField(verbose_name='CPU Cores')),
                ('memory', models.IntegerField(verbose_name='Memory (GB)')),
                ('database_type', models.CharField(max_length=255, verbose_name='Database Type')),
            ],
            options={
                'verbose_name': 'Database Server',
                'verbose_name_plural': 'Database Servers',
            },
        ),
        migrations.CreateModel(
            name='GeoDNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.IntegerField(verbose_name='Active Record')),
                ('load_balancing_method', models.CharField(max_length=255, verbose_name='Load Balancing Method')),
                ('dns_zone', models.CharField(max_length=255, verbose_name='DNS Zone')),
            ],
            options={
                'verbose_name': 'GeoDNS',
                'verbose_name_plural': 'GeoDNS',
            },
        ),
        migrations.CreateModel(
            name='HighCapacitySAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.IntegerField(verbose_name='Active Record')),
                ('storage_capacity', models.IntegerField(verbose_name='Storage Capacity (GB)')),
                ('redundancy_level', models.IntegerField(verbose_name='Redundancy Level')),
            ],
            options={
                'verbose_name': 'High Capacity SAN',
                'verbose_name_plural': 'High Capacity SANs',
            },
        ),
        migrations.CreateModel(
            name='HighPerformanceSAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.IntegerField(verbose_name='Active Record')),
                ('storage_capacity', models.IntegerField(verbose_name='Storage Capacity (GB)')),
                ('iops', models.IntegerField(verbose_name='IOPS')),
            ],
            options={
                'verbose_name': 'High Performance SAN',
                'verbose_name_plural': 'High Performance SANs',
            },
        ),
        migrations.CreateModel(
            name='LoadBalancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.IntegerField(verbose_name='Active Record')),
                ('virtual_servers', models.IntegerField(verbose_name='Number of Virtual Servers')),
                ('pool_size', models.IntegerField(verbose_name='Pool Size')),
            ],
            options={
                'verbose_name': 'Load Balancer',
                'verbose_name_plural': 'Load Balancers',
            },
        ),
        migrations.CreateModel(
            name='WebServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_record', models.IntegerField(verbose_name='Active Record')),
                ('cpu', models.IntegerField(verbose_name='CPU Cores')),
                ('memory', models.IntegerField(verbose_name='Memory (GB)')),
                ('domain', models.CharField(max_length=255, verbose_name='Domain')),
            ],
            options={
                'verbose_name': 'Web Server',
                'verbose_name_plural': 'Web Servers',
            },
        ),
    ]
