# Generated by Django 3.2.6 on 2021-08-20 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Software Publisher Name')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Software Publisher Slug')),
                ('status', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Software Name')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('status', models.BooleanField(default=False, verbose_name='Active')),
                ('version', models.CharField(max_length=200, unique=True, verbose_name='Software Version')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.publisher')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Software',
                'ordering': ('id', 'name'),
                'unique_together': {('name', 'publisher')},
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Server Name')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('status', models.BooleanField(default=False, verbose_name='Active')),
                ('software', models.ManyToManyField(blank=True, to='servers.Software')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'ordering': ('id', 'name'),
            },
        ),
    ]
