# Generated by Django 3.2.6 on 2021-08-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='version',
            field=models.CharField(max_length=200, null=True, verbose_name='Software Version'),
        ),
    ]
